name: CI Database

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DATABASE: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_ROOT_PASSWORD: root
        ports:
          - '5433:5432'
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download dependencies
        run: npm install

      - name: Verify project lint and try to fix it
        run: npm run lint:fix

      - name: Run the tests from project
        run: npm run test
